// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: person/person.proto

package person

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchServiceClient interface {
	//
	//rpc Search(PersonReq) returns(PersonRes) {
	//option(google.api.http) = {
	//post:"api/person"
	//body:"*"
	//};
	//};
	//
	SearchIn(ctx context.Context, opts ...grpc.CallOption) (SearchService_SearchInClient, error)
}

type searchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchServiceClient(cc grpc.ClientConnInterface) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) SearchIn(ctx context.Context, opts ...grpc.CallOption) (SearchService_SearchInClient, error) {
	stream, err := c.cc.NewStream(ctx, &SearchService_ServiceDesc.Streams[0], "/person.SearchService/SearchIn", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchServiceSearchInClient{stream}
	return x, nil
}

type SearchService_SearchInClient interface {
	Send(*PersonReq) error
	CloseAndRecv() (*PersonRes, error)
	grpc.ClientStream
}

type searchServiceSearchInClient struct {
	grpc.ClientStream
}

func (x *searchServiceSearchInClient) Send(m *PersonReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *searchServiceSearchInClient) CloseAndRecv() (*PersonRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PersonRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServiceServer is the server API for SearchService service.
// All implementations must embed UnimplementedSearchServiceServer
// for forward compatibility
type SearchServiceServer interface {
	//
	//rpc Search(PersonReq) returns(PersonRes) {
	//option(google.api.http) = {
	//post:"api/person"
	//body:"*"
	//};
	//};
	//
	SearchIn(SearchService_SearchInServer) error
	mustEmbedUnimplementedSearchServiceServer()
}

// UnimplementedSearchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSearchServiceServer struct {
}

func (UnimplementedSearchServiceServer) SearchIn(SearchService_SearchInServer) error {
	return status.Errorf(codes.Unimplemented, "method SearchIn not implemented")
}
func (UnimplementedSearchServiceServer) mustEmbedUnimplementedSearchServiceServer() {}

// UnsafeSearchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchServiceServer will
// result in compilation errors.
type UnsafeSearchServiceServer interface {
	mustEmbedUnimplementedSearchServiceServer()
}

func RegisterSearchServiceServer(s grpc.ServiceRegistrar, srv SearchServiceServer) {
	s.RegisterService(&SearchService_ServiceDesc, srv)
}

func _SearchService_SearchIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SearchServiceServer).SearchIn(&searchServiceSearchInServer{stream})
}

type SearchService_SearchInServer interface {
	SendAndClose(*PersonRes) error
	Recv() (*PersonReq, error)
	grpc.ServerStream
}

type searchServiceSearchInServer struct {
	grpc.ServerStream
}

func (x *searchServiceSearchInServer) SendAndClose(m *PersonRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *searchServiceSearchInServer) Recv() (*PersonReq, error) {
	m := new(PersonReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchService_ServiceDesc is the grpc.ServiceDesc for SearchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "person.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchIn",
			Handler:       _SearchService_SearchIn_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "person/person.proto",
}
